const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding NGOConnect database...");

  const passwordHash = await bcrypt.hash("password123", 10);

  // Donor
  const donor = await prisma.user.upsert({
    where: { email: "rahul.mehta@example.com" },
    update: {},
    create: {
      name: "Rahul Mehta",
      email: "rahul.mehta@example.com",
      passwordHash,
      role: "DONOR",
      phone: "+91 98765 43210",
      impactScore: 742,
      level: "PLATINUM",
      volunteerHours: 12,
    },
  });

  // Organization owner accounts + organizations
  const orgSeeds = [
    {
      email: "contact@ashavidya.org",
      name: "Asha Vidya School for the Blind",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Plot 14, Karve Road, Kothrud",
      lat: 18.5074,
      lng: 73.8077,
      about: "Asha Vidya runs a residential school for visually impaired children, offering Braille education, mobility training and vocational skills.",
      coordinatorName: "Mrs. Sunita Deshmukh",
      phone: "+91 98220 11234",
      studentCount: 180,
      teacherCount: 22,
      staffCount: 34,
      hostelAvailable: true,
      currentBeneficiaries: 210,
      servicesOffered: ["Braille Education", "Mobility Training", "Vocational Skills", "Residential Hostel"],
      requirements: [
        { itemName: "Rice", category: "Food", requiredQty: 50, availableQty: 20, unit: "kg", priority: "HIGH" },
        { itemName: "Braille Slates", category: "Education", requiredQty: 40, availableQty: 5, unit: "units", priority: "CRITICAL" },
      ],
    },
    {
      email: "gidd.pune@gov.in",
      name: "Government Institute for the Deaf & Dumb",
      category: "GOVERNMENT",
      city: "Pune, Maharashtra",
      address: "Sector 9, Civil Lines, Pune",
      lat: 18.5204,
      lng: 73.8567,
      about: "A state-run institution providing sign-language based education and speech therapy to hearing and speech impaired students.",
      coordinatorName: "Mr. Ramesh Patil",
      phone: "+91 71223 45678",
      studentCount: 260,
      teacherCount: 31,
      staffCount: 45,
      hostelAvailable: true,
      currentBeneficiaries: 305,
      servicesOffered: ["Sign Language Education", "Speech Therapy", "Skill Development"],
      requirements: [
        { itemName: "Hearing Aid Batteries", category: "Medical", requiredQty: 500, availableQty: 60, unit: "units", priority: "CRITICAL" },
      ],
    },
    {
      email: "care@shantiniwas.org",
      name: "Shanti Niwas Old Age Home",
      category: "OLD_AGE_HOME",
      city: "Pune, Maharashtra",
      address: "Baner-Pashan Link Road",
      lat: 18.5590,
      lng: 73.7868,
      about: "Shanti Niwas provides shelter, medical care and companionship to elderly residents, many of them without family support.",
      coordinatorName: "Mr. Anil Kulkarni",
      phone: "+91 98221 76543",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 19,
      hostelAvailable: true,
      currentBeneficiaries: 68,
      servicesOffered: ["Medical Care", "Physiotherapy", "Nutrition", "Recreation"],
      requirements: [
        { itemName: "Diapers (Adult)", category: "Medical", requiredQty: 300, availableQty: 150, unit: "units", priority: "HIGH" },
      ],
    },
    {
      email: "trust@gopalgaushala.org",
      name: "Gopal Gaushala Trust",
      category: "ANIMAL_SHELTER",
      city: "Pune, Maharashtra",
      address: "Chakan-Talegaon Road",
      lat: 18.7621,
      lng: 73.8478,
      about: "Gopal Gaushala shelters abandoned and injured cattle, providing fodder, veterinary care, and rehabilitation.",
      coordinatorName: "Mr. Vishnu Yadav",
      phone: "+91 98230 98761",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 27,
      hostelAvailable: false,
      currentBeneficiaries: 420,
      servicesOffered: ["Veterinary Care", "Fodder Supply", "Rescue & Rehabilitation"],
      requirements: [
        { itemName: "Dry Fodder", category: "Food", requiredQty: 2000, availableQty: 600, unit: "kg", priority: "CRITICAL" },
      ],
    },
    {
      email: "contact@snehfoundationindia.org",
      name: "SNEH Foundation",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Pimpri-Chinchwad, Pune",
      lat: 18.6298,
      lng: 73.7997,
      about: "SNEH Foundation improves health, education, nutrition and community well-being for underserved children, women and families in Pune.",
      coordinatorName: "Mr. Sunil Joshi",
      phone: "+91 20 2740 7700",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 18,
      hostelAvailable: false,
      currentBeneficiaries: 320,
      servicesOffered: ["Education", "Health Camps", "Nutrition", "Community Welfare"],
      requirements: [{ itemName: "School Supplies", category: "Education", requiredQty: 180, availableQty: 70, unit: "sets", priority: "HIGH" }],
    },
    {
      email: "contact@ishanyafoundation.org",
      name: "Ishanya Foundation",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Kondhwa, Pune",
      lat: 18.4606,
      lng: 73.8830,
      about: "Ishanya Foundation works on women empowerment, livelihood programmes, health and education across Pune and nearby villages.",
      coordinatorName: "Ms. Priya Sharma",
      phone: "+91 20 2683 1244",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 16,
      hostelAvailable: false,
      currentBeneficiaries: 240,
      servicesOffered: ["Women Empowerment", "Livelihood Support", "Health", "Education"],
      requirements: [{ itemName: "Hygiene Kits", category: "Essentials", requiredQty: 120, availableQty: 40, unit: "kits", priority: "MEDIUM" }],
    },
    {
      email: "contact@theaakarfoundation.org",
      name: "Aakar Foundation",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Wakad, Pune",
      lat: 18.5961,
      lng: 73.7620,
      about: "Aakar Foundation supports underprivileged children and families in Pune through education, essentials and sports initiatives.",
      coordinatorName: "Mrs. Neeta Deshpande",
      phone: "+91 20 2723 0101",
      studentCount: 220,
      teacherCount: 18,
      staffCount: 24,
      hostelAvailable: false,
      currentBeneficiaries: 410,
      servicesOffered: ["Education", "Essentials Distribution", "Awareness", "Sports"],
      requirements: [{ itemName: "Books", category: "Education", requiredQty: 300, availableQty: 90, unit: "sets", priority: "HIGH" }],
    },
    {
      email: "contact@deepgriha.org",
      name: "Deep Griha Society",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Mundhwa, Pune",
      lat: 18.5338,
      lng: 73.9197,
      about: "Deep Griha Society runs family welfare programs for low-income communities in Pune through education, healthcare and child development.",
      coordinatorName: "Mr. Sandeep Kharat",
      phone: "+91 20 2685 9000",
      studentCount: 180,
      teacherCount: 22,
      staffCount: 28,
      hostelAvailable: false,
      currentBeneficiaries: 360,
      servicesOffered: ["Child Development", "Healthcare", "Women Empowerment", "Family Welfare"],
      requirements: [{ itemName: "Nutrition Packs", category: "Food", requiredQty: 150, availableQty: 60, unit: "packs", priority: "HIGH" }],
    },
    {
      email: "contact@muktanganedu.org",
      name: "Muktangan Education Trust",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Kothrud, Pune",
      lat: 18.5044,
      lng: 73.8135,
      about: "Muktangan Education Trust provides quality learning and support to children in underserved urban communities across Pune.",
      coordinatorName: "Dr. Kavita Bhat",
      phone: "+91 20 2545 6000",
      studentCount: 320,
      teacherCount: 24,
      staffCount: 30,
      hostelAvailable: false,
      currentBeneficiaries: 340,
      servicesOffered: ["Early Learning", "Remedial Education", "Teacher Support", "Community Learning"],
      requirements: [{ itemName: "Notebooks", category: "Education", requiredQty: 400, availableQty: 180, unit: "sets", priority: "MEDIUM" }],
    },
    {
      email: "contact@akanksha.org",
      name: "The Akanksha Foundation",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Shivajinagar, Pune",
      lat: 18.5314,
      lng: 73.8446,
      about: "The Akanksha Foundation runs community and center-based learning programs for children in Pune.",
      coordinatorName: "Ms. Sneha Nair",
      phone: "+91 20 2567 4422",
      studentCount: 280,
      teacherCount: 19,
      staffCount: 27,
      hostelAvailable: false,
      currentBeneficiaries: 310,
      servicesOffered: ["Education", "After School Support", "Tutoring", "Student Development"],
      requirements: [{ itemName: "Stationery", category: "Education", requiredQty: 250, availableQty: 90, unit: "sets", priority: "MEDIUM" }],
    },
    {
      email: "pune@teachforindia.org",
      name: "Teach For India",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Camp, Pune",
      lat: 18.5108,
      lng: 73.8797,
      about: "Teach For India expands educational opportunity in Pune through a fellowship-based model for teachers and leaders.",
      coordinatorName: "Mr. Aditya Rao",
      phone: "+91 20 6620 4700",
      studentCount: 260,
      teacherCount: 15,
      staffCount: 19,
      hostelAvailable: false,
      currentBeneficiaries: 290,
      servicesOffered: ["Teaching Fellowship", "Leadership Development", "Education Access", "Community Programs"],
      requirements: [{ itemName: "Laptop Chargers", category: "Education", requiredQty: 80, availableQty: 20, unit: "units", priority: "HIGH" }],
    },
    {
      email: "contact@yuvaunstoppable.org",
      name: "Yuva Unstoppable",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Kharadi, Pune",
      lat: 18.5517,
      lng: 73.9268,
      about: "Yuva Unstoppable helps young people in Pune build leadership, entrepreneurship and civic action through community-led programs.",
      coordinatorName: "Ms. Richa Kulkarni",
      phone: "+91 20 2970 4000",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 12,
      hostelAvailable: false,
      currentBeneficiaries: 180,
      servicesOffered: ["Youth Leadership", "Skill Building", "Volunteering", "Community Action"],
      requirements: [{ itemName: "Volunteer Kits", category: "Essentials", requiredQty: 100, availableQty: 35, unit: "kits", priority: "MEDIUM" }],
    },
    {
      email: "pune@helpageindia.org",
      name: "HelpAge India - Pune Chapter",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Pune Cantonment",
      lat: 18.5292,
      lng: 73.8758,
      about: "HelpAge India supports older adults in Pune through health camps, social support and welfare outreach.",
      coordinatorName: "Mr. Pravin Bhosale",
      phone: "+91 20 2633 2555",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 14,
      hostelAvailable: false,
      currentBeneficiaries: 160,
      servicesOffered: ["Senior Care", "Health Camps", "Welfare Outreach", "Emergency Support"],
      requirements: [{ itemName: "Wheelchairs", category: "Medical", requiredQty: 40, availableQty: 12, unit: "units", priority: "HIGH" }],
    },
    {
      email: "pune@salvationarmy.org",
      name: "The Salvation Army - Pune",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "Hadapsar, Pune",
      lat: 18.5006,
      lng: 73.9328,
      about: "The Salvation Army in Pune provides shelter, education, healthcare and emergency relief services for vulnerable families.",
      coordinatorName: "Maj. Sanjay Fernandes",
      phone: "+91 20 2699 1244",
      studentCount: 80,
      teacherCount: 10,
      staffCount: 26,
      hostelAvailable: true,
      currentBeneficiaries: 220,
      servicesOffered: ["Shelter", "Education", "Healthcare", "Emergency Relief"],
      requirements: [{ itemName: "Blankets", category: "Essentials", requiredQty: 90, availableQty: 25, unit: "units", priority: "HIGH" }],
    },
    {
      email: "contact@puneblindmensassociation.org",
      name: "Pune Blind Men’s Association",
      category: "NGO",
      city: "Pune, Maharashtra",
      address: "M G Road, Pune",
      lat: 18.5196,
      lng: 73.8567,
      about: "Pune Blind Men’s Association supports visually impaired persons through rehabilitation services and community support.",
      coordinatorName: "Ms. Asha Patil",
      phone: "+91 20 2612 4333",
      studentCount: 0,
      teacherCount: 0,
      staffCount: 11,
      hostelAvailable: false,
      currentBeneficiaries: 150,
      servicesOffered: ["Rehabilitation", "Daily Care", "Skill Training", "Community Support"],
      requirements: [{ itemName: "Braille Books", category: "Education", requiredQty: 120, availableQty: 40, unit: "books", priority: "MEDIUM" }],
    },
  ];

  for (const seed of orgSeeds) {
    const ownerUser = await prisma.user.upsert({
      where: { email: seed.email },
      update: {},
      create: { name: seed.name, email: seed.email, passwordHash, role: "ORGANIZATION" },
    });

    const org = await prisma.organization.upsert({
      where: { userId: ownerUser.id },
      update: {},
      create: {
        userId: ownerUser.id,
        name: seed.name,
        category: seed.category,
        verified: true,
        about: seed.about,
        address: seed.address || seed.city,
        city: seed.city,
        lat: seed.lat,
        lng: seed.lng,
        coordinatorName: seed.coordinatorName,
        phone: seed.phone,
        email: seed.email,
        website: `www.${seed.email.split("@")[1]}`,
        studentCount: seed.studentCount,
        teacherCount: seed.teacherCount,
        staffCount: seed.staffCount,
        hostelAvailable: seed.hostelAvailable,
        currentBeneficiaries: seed.currentBeneficiaries,
        servicesOffered: seed.servicesOffered,
        needsFulfilledPct: 55,
        mealsSupported: 10000,
        studentsBenefited: seed.studentCount,
        totalDonations: 120,
      },
    });

    for (const r of seed.requirements) {
      await prisma.requirement.create({
        data: {
          organizationId: org.id,
          itemName: r.itemName,
          category: r.category,
          requiredQty: r.requiredQty,
          availableQty: r.availableQty,
          unit: r.unit,
          priority: r.priority,
          status: r.availableQty >= r.requiredQty ? "FULFILLED" : r.availableQty > 0 ? "PARTIAL" : "OPEN",
        },
      });
    }
  }

  // A sample completed donation with a badge + certificate, to show the
  // reward pipeline pre-populated.
  const firstOrg = await prisma.organization.findFirst({ where: { name: orgSeeds[0].name } });
  if (firstOrg) {
    const donation = await prisma.donation.create({
      data: {
        donorId: donor.id,
        organizationId: firstOrg.id,
        status: "COMPLETED",
        approvedBy: firstOrg.coordinatorName,
        certificateAvailable: true,
        items: { create: [{ itemName: "Rice", qty: 20, unit: "kg" }] },
      },
    });

    const badge = await prisma.badge.upsert({
      where: { name: "First Donation" },
      update: {},
      create: { name: "First Donation", description: "Made your very first donation", icon: "Sparkles" },
    });
    await prisma.userBadge.upsert({
      where: { userId_badgeId: { userId: donor.id, badgeId: badge.id } },
      update: {},
      create: { userId: donor.id, badgeId: badge.id, donationId: donation.id },
    });
    await prisma.certificate.upsert({
      where: { donationId: donation.id },
      update: {},
      create: { donationId: donation.id, userId: donor.id, fileUrl: `/certificates/${donation.id}.pdf` },
    });
  }

  console.log("Seed complete. Demo login: rahul.mehta@example.com / password123 (donor)");
  console.log("Org logins: contact@ashavidya.org, gidd.pune@gov.in, care@shantiniwas.org, trust@gopalgaushala.org, contact@snehfoundationindia.org, contact@ishanyafoundation.org, contact@theaakarfoundation.org, contact@deepgriha.org, contact@muktanganedu.org, contact@akanksha.org, pune@teachforindia.org, contact@yuvaunstoppable.org, pune@helpageindia.org, pune@salvationarmy.org, contact@puneblindmensassociation.org (password: password123)");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
